export const MOCK_COMPANIES = [
  {
    id: 1,
    name: "뤼이드",
    logo: "/icons/뤼이드.png",
    logoContain: true,
    logoInitial: "R",
    logoColor: "#1B3A6B",
    description: "AI 기반 적응형 학습 솔루션을 개발하는 에듀테크 스타트업입니다. 개인화된 학습 경험을 통해 학습 효율을 극대화합니다.",
    category: "에듀테크",
    myCount: 9804,
    compareCount: 3201,
  },
  {
    id: 2,
    name: "매스프레소",
    logo: "/icons/매스프레소.png",
    logoInitial: "M",
    logoColor: "#FF6B35",
    description: "수학 문제 풀이 AI 앱 '콴다'를 운영하는 에듀테크 스타트업입니다. 전 세계 학생들의 학습을 돕고 있습니다.",
    category: "에듀테크",
    myCount: 8766,
    compareCount: 4108,
  },
  {
    id: 3,
    name: "코드잇",
    logo: "/icons/코드잇.png",
    logoInitial: "C",
    logoColor: "#7B3FE4",
    description: "온라인 코딩 교육 서비스를 운영하는 에듀테크 스타트업입니다. 코딩 교육에 대한 수준 높은 커리큘럼을 제공합니다.",
    category: "에듀테크",
    myCount: 8142,
    compareCount: 7506,
  },
  {
    id: 4,
    name: "엘리스",
    logo: "/icons/엘리스.png",
    logoContain: true,
    logoInitial: "E",
    logoColor: "#6B3FE4",
    description: "AI 기반 교육 플랫폼을 운영하는 에듀테크 스타트업입니다. 기업 맞춤형 교육 솔루션을 제공합니다.",
    category: "에듀테크",
    myCount: 7204,
    compareCount: 9224,
  },
  {
    id: 5,
    name: "아이헤이트플라잉버드",
    logo: "/icons/밀당PT.png",
    logoInitial: "아",
    logoColor: "#1A1A1A",
    description: "1:1 퍼스널 트레이닝 매칭 플랫폼을 운영하는 헬스테크 스타트업입니다. 전문 트레이너와 고객을 연결합니다.",
    category: "헬스테크",
    myCount: 5763,
    compareCount: 5763,
  },
  {
    id: 6,
    name: "클래스101",
    logo: "/icons/클래스101.png",
    logoContain: true,
    logoInitial: "K",
    logoColor: "#FF4444",
    description: "크리에이터와 학습자를 연결하는 온라인 클래스 플랫폼입니다. 다양한 분야의 취미 및 직무 교육을 제공합니다.",
    category: "에듀테크",
    myCount: 4004,
    compareCount: 5883,
  },
  {
    id: 7,
    name: "스파르타코딩클럽",
    logo: "/icons/스파르타코딩클럽.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "S",
    logoColor: "#E8483A",
    description: "비개발자를 위한 코딩 교육 서비스를 운영하는 에듀테크 스타트업입니다. 실무 중심의 교육 커리큘럼을 제공합니다.",
    category: "에듀테크",
    myCount: 3951,
    compareCount: 504,
  },
  {
    id: 8,
    name: "채널톡",
    logo: "/icons/채널톡.jpg",
    logoContain: true,
    logoFull: true,
    logoInitial: "채",
    logoColor: "#3D7FFF",
    description: "B2B 고객 커뮤니케이션 플랫폼을 운영하는 스타트업입니다. 채팅, CRM, 마케팅 자동화를 통합한 올인원 솔루션을 제공합니다.",
    category: "SaaS",
    myCount: 1768,
    compareCount: 2375,
  },
  {
    id: 9,
    name: "탈잉",
    logo: "/icons/탈잉.png",
    logoContain: true,
    logoInitial: "T",
    logoColor: "#00C4B4",
    description: "재능 공유 플랫폼을 운영하는 스타트업입니다. 누구나 선생님이 되어 자신의 재능을 나눌 수 있는 서비스를 제공합니다.",
    category: "에듀테크",
    myCount: 941,
    compareCount: 1481,
  },
  {
    id: 10,
    name: "뤼이드",
    logo: "/icons/뤼이드.png",
    logoContain: true,
    logoInitial: "R",
    logoColor: "#1B3A6B",
    description: "AI 기반 적응형 학습 솔루션을 개발하는 에듀테크 스타트업입니다. 개인화된 학습 경험을 통해 학습 효율을 극대화합니다.",
    category: "에듀테크",
    myCount: 867,
    compareCount: 675,
  },
  {
    id: 11,
    name: "토스",
    logo: "/icons/토스.png",
    logoContain: true,
    logoFull: true,
    logoInitial: "T",
    logoColor: "#0064FF",
    description: "간편 송금 서비스를 시작으로 종합 금융 플랫폼으로 성장한 핀테크 스타트업입니다.",
    category: "핀테크",
    myCount: 754,
    compareCount: 1203,
  },
  {
    id: 12,
    name: "뱅크샐러드",
    logo: "/icons/뱅크샐러드.jpeg",
    logoContain: true,
    logoFull: true,
    logoInitial: "B",
    logoColor: "#00C471",
    description: "개인 자산 관리 서비스를 제공하는 핀테크 스타트업입니다. 금융 데이터 분석을 통한 맞춤형 재테크 서비스를 제공합니다.",
    category: "핀테크",
    myCount: 623,
    compareCount: 879,
  },
  {
    id: 13,
    name: "마켓컬리",
    logo: "/icons/마켓컬리.png",
    logoContain: true,
    logoInitial: "M",
    logoColor: "#5F0080",
    description: "새벽 배송 서비스를 운영하는 커머스 스타트업입니다. 신선하고 품질 좋은 식품을 빠르게 배송합니다.",
    category: "커머스",
    myCount: 512,
    compareCount: 634,
  },
  {
    id: 14,
    name: "오늘의집",
    logo: "/icons/오늘의집.jpg",
    logoContain: true,
    logoInitial: "O",
    logoColor: "#4CAF50",
    description: "인테리어 커머스 및 커뮤니티 플랫폼을 운영하는 스타트업입니다. 인테리어 정보 공유와 가구 구매를 연결합니다.",
    category: "라이프스타일",
    myCount: 438,
    compareCount: 521,
  },
  {
    id: 15,
    name: "당근마켓",
    logo: "/icons/당근마켓.svg",
    logoContain: true,
    logoInitial: "D",
    logoColor: "#FF6F0F",
    description: "지역 기반 중고 거래 플랫폼을 운영하는 스타트업입니다. 동네 이웃과 안전하고 편리하게 거래할 수 있는 서비스입니다.",
    category: "로컬커머스",
    myCount: 321,
    compareCount: 445,
  },
  {
    id: 16,
    name: "야놀자",
    logo: "/icons/야놀자.png",
    logoContain: true,
    logoInitial: "Y",
    logoColor: "#FF4081",
    description: "숙박 및 여행 플랫폼을 운영하는 여행테크 스타트업입니다. 다양한 숙박 시설 예약 서비스와 여행 콘텐츠를 제공합니다.",
    category: "여행/숙박",
    myCount: 289,
    compareCount: 367,
  },
  {
    id: 17,
    name: "직방",
    logo: "/icons/직방.png",
    logoContain: true,
    logoFull: true,
    logoInitial: "J",
    logoColor: "#1565C0",
    description: "부동산 정보 플랫폼을 운영하는 프롭테크 스타트업입니다. 원룸, 아파트 등 다양한 주거 정보를 제공합니다.",
    category: "프롭테크",
    myCount: 201,
    compareCount: 298,
  },
  {
    id: 18,
    name: "무신사",
    logo: "/icons/무신사.png",
    logoContain: true,
    logoInitial: "M",
    logoColor: "#222222",
    description: "패션 커머스 플랫폼을 운영하는 스타트업입니다. 다양한 패션 브랜드와 소비자를 연결하는 온라인 패션 스토어입니다.",
    category: "패션",
    myCount: 178,
    compareCount: 234,
  },
  {
    id: 19,
    name: "닥터다이어리",
    logo: "/icons/닥터다이어리.jpg",
    logoContain: true,
    logoInitial: "D",
    logoColor: "#26A69A",
    description: "당뇨 환자를 위한 건강 관리 플랫폼을 운영하는 헬스케어 스타트업입니다. 혈당 기록 및 관리 서비스를 제공합니다.",
    category: "헬스케어",
    myCount: 134,
    compareCount: 189,
  },
  {
    id: 20,
    name: "눔",
    logo: "/icons/눔.jpg",
    logoContain: true,
    logoInitial: "N",
    logoColor: "#FF7043",
    description: "심리학 기반 체중 감량 앱을 운영하는 헬스테크 스타트업입니다. 행동 변화 과학을 적용한 건강 관리 서비스를 제공합니다.",
    category: "헬스테크",
    myCount: 98,
    compareCount: 145,
  },
  {
    id: 21,
    name: "크래프톤",
    logo: "/icons/크래프톤.png",
    logoContain: true,
    logoInitial: "K",
    logoColor: "#1A1A2E",
    description: "배틀그라운드를 개발한 글로벌 게임 스타트업입니다. 세계적인 배틀로얄 장르를 개척한 게임 개발사입니다.",
    category: "게임",
    myCount: 87,
    compareCount: 132,
  },
  {
    id: 22,
    name: "하이퍼커넥트",
    logoInitial: "H",
    logoColor: "#FF5C5C",
    description: "영상 기반 소셜 미디어 플랫폼 '아자르'를 운영하는 스타트업입니다. 전 세계 사용자를 실시간으로 연결합니다.",
    category: "소셜",
    myCount: 76,
    compareCount: 98,
  },
  {
    id: 23,
    name: "버킷플레이스",
    logo: "/icons/오늘의집.jpg",
    logoContain: true,
    logoInitial: "B",
    logoColor: "#3CB371",
    description: "홈 인테리어 플랫폼 '오늘의집'을 운영하는 스타트업입니다. 인테리어 커뮤니티와 커머스를 결합한 서비스입니다.",
    category: "라이프스타일",
    myCount: 65,
    compareCount: 87,
  },
  {
    id: 24,
    name: "두나무",
    logo: "/icons/두나무.jpg",
    logoContain: true,
    logoInitial: "D",
    logoColor: "#F7A600",
    description: "암호화폐 거래소 '업비트'를 운영하는 핀테크 스타트업입니다. 국내 최대 디지털 자산 거래 플랫폼입니다.",
    category: "핀테크",
    myCount: 54,
    compareCount: 76,
  },
  {
    id: 25,
    name: "비바리퍼블리카",
    logo: "/icons/토스.png",
    logoContain: true,
    logoFull: true,
    logoInitial: "V",
    logoColor: "#0064FF",
    description: "간편 금융 서비스 '토스'를 운영하는 핀테크 스타트업입니다. 혁신적인 UX로 금융의 문턱을 낮추고 있습니다.",
    category: "핀테크",
    myCount: 43,
    compareCount: 65,
  },
  {
    id: 26,
    name: "컬리",
    logo: "/icons/마켓컬리.png",
    logoContain: true,
    logoInitial: "K",
    logoColor: "#6A0DAD",
    description: "신선식품 새벽배송 서비스를 운영하는 커머스 스타트업입니다. 엄선된 식품을 빠르고 신선하게 배송합니다.",
    category: "커머스",
    myCount: 39,
    compareCount: 54,
  },
  {
    id: 27,
    name: "원티드랩",
    logo: "/icons/원티드랩.png",
    logoContain: true,
    logoInitial: "W",
    logoColor: "#355CE9",
    description: "AI 기반 채용 플랫폼을 운영하는 HR테크 스타트업입니다. 인재와 기업을 효율적으로 매칭해주는 서비스입니다.",
    category: "HR테크",
    myCount: 34,
    compareCount: 48,
  },
  {
    id: 28,
    name: "리멤버",
    logo: "/icons/리멤버.png",
    logoContain: true,
    logoInitial: "R",
    logoColor: "#2B5CE6",
    description: "명함 관리 및 비즈니스 네트워킹 플랫폼을 운영하는 스타트업입니다. 디지털 명함과 커리어 관리 서비스를 제공합니다.",
    category: "HR테크",
    myCount: 28,
    compareCount: 41,
  },
  {
    id: 29,
    name: "카카오페이",
    logo: "/icons/카카오페이.png",
    logoContain: true,
    logoMax: true,
    logoBg: "#F7E600",
    logoInitial: "K",
    logoColor: "#F7E600",
    description: "카카오 기반 간편 결제 및 금융 서비스를 운영하는 핀테크 기업입니다. 일상 속 금융을 더 쉽고 편리하게 제공합니다.",
    category: "핀테크",
    myCount: 23,
    compareCount: 35,
  },
  {
    id: 30,
    name: "쏘카",
    logo: "/icons/쏘카.png",
    logoContain: true,
    logoInitial: "S",
    logoColor: "#00C4B4",
    description: "카셰어링 서비스를 운영하는 모빌리티 스타트업입니다. 합리적인 가격으로 차량을 필요할 때 빌려 사용할 수 있습니다.",
    category: "모빌리티",
    myCount: 19,
    compareCount: 28,
  },
  {
    id: 31,
    name: "타다",
    logo: "/icons/타다.jpeg",
    logoContain: true,
    logoMax: true,
    logoInitial: "T",
    logoColor: "#1A1A1A",
    description: "혁신적인 모빌리티 서비스를 운영하는 스타트업입니다. 편리하고 안전한 이동 경험을 제공합니다.",
    category: "모빌리티",
    myCount: 16,
    compareCount: 22,
  },
  {
    id: 32,
    name: "플렉스",
    logo: "/icons/플렉스.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "F",
    logoColor: "#6C5CE7",
    description: "HR SaaS 플랫폼을 운영하는 스타트업입니다. 기업 인사 관리를 디지털화하는 클라우드 솔루션을 제공합니다.",
    category: "HR테크",
    myCount: 14,
    compareCount: 19,
  },
  {
    id: 33,
    name: "센드버드",
    logo: "/icons/센드버드.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "S",
    logoColor: "#742DDD",
    description: "채팅 API 및 인앱 메시징 플랫폼을 제공하는 B2B 스타트업입니다. 글로벌 기업들의 커뮤니케이션을 지원합니다.",
    category: "SaaS",
    myCount: 11,
    compareCount: 16,
  },
  {
    id: 34,
    name: "몰로코",
    logo: "/icons/몰로코.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "M",
    logoColor: "#FF6B35",
    description: "머신러닝 기반 광고 플랫폼을 운영하는 애드테크 스타트업입니다. AI로 광고 효율을 극대화하는 솔루션을 제공합니다.",
    category: "애드테크",
    myCount: 9,
    compareCount: 13,
  },
  {
    id: 35,
    name: "에이블리",
    logo: "/icons/에이블리.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "A",
    logoColor: "#FF4081",
    description: "AI 기반 여성 패션 커머스 플랫폼을 운영하는 스타트업입니다. 개인화 추천으로 원하는 스타일을 쉽게 찾을 수 있습니다.",
    category: "패션",
    myCount: 7,
    compareCount: 11,
  },
  {
    id: 36,
    name: "지그재그",
    logo: "/icons/지그재그.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "Z",
    logoColor: "#FF5D87",
    description: "여성 패션 쇼핑 앱을 운영하는 커머스 스타트업입니다. 다양한 쇼핑몰을 한 곳에서 편리하게 이용할 수 있습니다.",
    category: "패션",
    myCount: 6,
    compareCount: 9,
  },
  {
    id: 37,
    name: "브랜디",
    logo: "/icons/브랜디.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "B",
    logoColor: "#FF3D78",
    description: "패션 커머스 및 풀필먼트 서비스를 운영하는 스타트업입니다. 셀러와 소비자를 연결하는 플랫폼을 제공합니다.",
    category: "패션",
    myCount: 5,
    compareCount: 7,
  },
  {
    id: 38,
    name: "식스샵",
    logo: "/icons/식스샵.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "6",
    logoColor: "#2D3436",
    description: "소상공인을 위한 온라인 쇼핑몰 창업 플랫폼을 운영하는 스타트업입니다. 누구나 쉽게 온라인 쇼핑몰을 만들 수 있습니다.",
    category: "커머스",
    myCount: 4,
    compareCount: 6,
  },
  {
    id: 39,
    name: "리디",
    logo: "/icons/리디.jpg",
    logoContain: true,
    logoMax: true,
    logoInitial: "R",
    logoColor: "#00B4D8",
    description: "전자책 및 웹툰 플랫폼을 운영하는 콘텐츠 스타트업입니다. 다양한 디지털 콘텐츠를 제공하는 종합 플랫폼입니다.",
    category: "콘텐츠",
    myCount: 3,
    compareCount: 5,
  },
  {
    id: 40,
    name: "왓챠",
    logo: "/icons/왓챠.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "W",
    logoColor: "#E50914",
    description: "OTT 스트리밍 서비스를 운영하는 콘텐츠 스타트업입니다. 영화, 드라마, 애니메이션 등 다양한 콘텐츠를 제공합니다.",
    category: "콘텐츠",
    myCount: 2,
    compareCount: 3,
  },
  {
    id: 41,
    name: "노트폴리오",
    logo: "/icons/노트폴리오.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "N",
    logoColor: "#333333",
    description: "크리에이터를 위한 포트폴리오 및 커뮤니티 플랫폼입니다. 디자이너, 작가 등 다양한 크리에이터들이 작품을 공유합니다.",
    category: "크리에이터",
    myCount: 2,
    compareCount: 2,
  },
  {
    id: 42,
    name: "점핏",
    logo: "/icons/점핏.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "J",
    logoColor: "#4A90E2",
    description: "개발자 특화 채용 플랫폼을 운영하는 HR테크 스타트업입니다. IT 직군 전문 채용 서비스를 제공합니다.",
    category: "HR테크",
    myCount: 1,
    compareCount: 2,
  },
  {
    id: 43,
    name: "카닥",
    logo: "/icons/카닥.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "K",
    logoColor: "#FF6B35",
    description: "자동차 수리 견적 비교 플랫폼을 운영하는 오토테크 스타트업입니다. 합리적인 자동차 관리를 도와줍니다.",
    category: "오토테크",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 44,
    name: "클래스유",
    logo: "/icons/클래스유.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "C",
    logoColor: "#FF8C00",
    description: "성인 교육 및 자기계발 온라인 플랫폼을 운영하는 에듀테크 스타트업입니다. 다양한 강의를 합리적인 가격에 제공합니다.",
    category: "에듀테크",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 45,
    name: "패스트파이브",
    logo: "/icons/패스트파이브.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "F",
    logoColor: "#2C3E50",
    description: "공유 오피스 서비스를 운영하는 프롭테크 스타트업입니다. 스타트업과 기업을 위한 유연한 업무 공간을 제공합니다.",
    category: "프롭테크",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 46,
    name: "스푼라디오",
    logo: "/icons/스푼.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "S",
    logoColor: "#7B2FBE",
    description: "오디오 스트리밍 및 라이브 방송 플랫폼을 운영하는 스타트업입니다. 누구나 DJ가 되어 방송할 수 있는 서비스입니다.",
    category: "미디어",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 47,
    name: "오피지지",
    logo: "/icons/OPGG.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "O",
    logoColor: "#1A237E",
    description: "게임 전적 검색 및 분석 서비스를 운영하는 게임테크 스타트업입니다. 리그오브레전드 등 다양한 게임 통계를 제공합니다.",
    category: "게임",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 48,
    name: "아이디어스",
    logo: "/icons/아이디어스.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "A",
    logoColor: "#E91E63",
    description: "핸드메이드 작품 거래 플랫폼을 운영하는 스타트업입니다. 작가와 소비자를 연결하는 수공예 마켓플레이스입니다.",
    category: "커머스",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 49,
    name: "트레바리",
    logo: "/icons/트레바리.jpeg",
    logoContain: true,
    logoMax: true,
    logoInitial: "T",
    logoColor: "#212121",
    description: "독서 모임 플랫폼을 운영하는 소셜 스타트업입니다. 취향이 맞는 사람들과 함께 책을 읽고 토론하는 서비스입니다.",
    category: "소셜",
    myCount: 1,
    compareCount: 1,
  },
  {
    id: 50,
    name: "퍼블리",
    logo: "/icons/퍼블리.png",
    logoContain: true,
    logoMax: true,
    logoInitial: "P",
    logoColor: "#00897B",
    description: "직장인을 위한 콘텐츠 구독 서비스를 운영하는 스타트업입니다. 커리어 성장에 필요한 인사이트를 제공합니다.",
    category: "콘텐츠",
    myCount: 1,
    compareCount: 1,
  },
];
